ANTLR_LIB = lib/antlr-4.13.2-complete.jar

SRC_DIR = src
OUT_DIR = bin
TEST_DIR = tests

GRAMMAR = $(SRC_DIR)/KobraV2.g4
CLASSPATH = ".:$(ANTLR_JAR):$(OUT_DIR)"

all:
    generate compile

generate:
    java -jar $(ANTLR_JAR) -Dlanguage=Java -visitor $(GRAMMAR)

compile:
    mkdir -p $(OUT_DIR)
    javac -cp $(ANTLR_JAR) -d $(OUT_DIR) $(SRC_DIR)/*.java

clean:
	rm -rf $(OUT_DIR)
	rm -f $(SRC_DIR)/*.tokens
	rm -f $(SRC_DIR)/*.interp
	rm -f $(SRC_DIR)/MiLenguajeLexer.java
	rm -f $(SRC_DIR)/MiLenguajeParser.java
	rm -f $(SRC_DIR)/MiLenguajeBaseListener.java
	rm -f $(SRC_DIR)/MiLenguajeBaseVisitor.java
	rm -f $(SRC_DIR)/MiLenguajeListener.java
	rm -f $(SRC_DIR)/MiLenguajeVisitor.java